config/routes.rb
Rails.application.routes.draw do
  

 
  resources :phone_nums
  match '/api/*other' => 'notes#opt', via: [:options]

  get '/api/users/clubs/abstracts/:category' => 'clubs#clubsbycategory' #按社团类别返回对应的社团列表
  get '/api/articles/activities/:page_id' => 'clubs#clubsactivity'#返回一个社团>的活动
  get '/api/users/clubs/abstract/:page_id' => 'clubs#clublist'#返回社团列表
  get '/api/clubs/detail' => 'clubs#returnmm'  #返回社团人数

  resources :comments
  resources :webmails
  resources :lists

  post '/api/users/register/checkiden' => 'users#checkiden' # 实名验证

  get '/api/articles/:article_id/comments' => 'comments#getcomments' # 获得当前文章评论

  post '/api/users/phone_num/verify/code' => 'users#verify_phone_sendcode'# 手机验证发送验证码
  post '/api/users/phone_num/verify' => 'users#verify_phone' # 验证验证码是否正确
  post 'GET /api/users/email/verify' => 'users#verify_email_send' # 验证邮箱，给邮箱寄信
  get '/api/users/email/verify/:uid/:hash_code' => 'users#verify_email' # 验证邮箱，邮箱点击链接返回

  post '/api/users/forgetpassword/email' => 'users#fp_email' # 忘记密码，邮箱
  get '/api/users/forgetpassword/email/verify/:uid/:hash_code' => 'users#fp_email_verify' # 忘记密码，邮箱转跳
  post '/api/users/forgetpassword/phone_num/send' => 'users#fp_phone_send' # 忘记密码，手机
  post '/api/users/forgetpassword/phone_num/verify' => 'users#fp_phone_verify' # 忘记密码，手机
  
  get '/api/users/detail' => 'users#detail'#返回个人信息
  post '/api/users/statistics' => 'users#statistics'#返回用户参加的社团个数和报名活动个数
  get '/api/users/clubs/all' => 'users#clublist'  
  get '/api/users/articles/activities/all' => 'users#activitylist'

  get '/api/clubs/members/all' => 'clubs#memberslist'#获取社团名单
  get 'api/clubs/users/export/:uid' => 'clubs#exportlist' #导出名单
  post '/api/clubs/members/forcequit' => 'clubs#forcequit' #强制退社
  get '/api/clubs/members/apply' => 'clubs#applicationlist' #申请人列表
  post '/api/clubs/members/apply/accept' => 'clubs#acceptapplication'#同意申请
  post '/api/clubs/members/apply/refuse' => 'clubs#refuseapplication'#拒绝申请  

  resources :informs
  resources :applications

  get '/api/users/register/check/:uid' => 'users#checkuid'
  post '/api/register' => 'users#register'
  post '/api/clubs/login' => 'clubs#login'
  post '/api/users/login' => 'users#login'
  post '/api/users/get_token_for_app' => 'users#get_token_for_app'
  get '/api/articles/:page_id/:club_id/:kind' => 'articles#abstracts'
  get '/api/articles/detail/:article_id' => 'articles#detail'
  get '/api/clubs/:uid/articles/:page_id' => 'clubs#getabstracts'
  get '/api/users/logout' => 'users#logout'
  get '/api/clubs/logout' => 'clubs#logout'
  post '/api/clubs/inform' => 'clubs#inform'
  post '/api/clubs/articles/:article_id/comments/reply/:reply_id' => 'clubs#reply'
  post '/api/users/articles/:article_id/comments/reply/:reply_id' => 'users#reply'
  post '/api/users/webmails/readall' => 'users#readall'
  post '/api/clubs/webmails/readall' => 'clubs#readall'
  post '/api/users/webmails/usergetcontent/:webmail_id' => 'users#usergetcontent'
   post '/api/clubs/webmails/clubgetcontent/:webmail_id' => 'clubs#clubgetcontent'
  post '/api/users/clubs/apply/:club_id' => 'users#apply'
  get '/api/users/articles/activities/cancel/:article_id' => 'users#cancel'

  get '/api/clubs/informs/all' => 'clubs#getinform'
  post '/api/clubs/articles/detail/create' => 'articles#create'
  post '/api/clubs/articles/detail/:article_id/change' => 'articles#show'
  post '/api/clubs/articles/detail/:article_id/update' => 'articles#update'
  post '/api/clubs/articles/detail/:article_id/delete' => 'articles#destroy' 
  post '/api/clubs/articles/detail/:article_id/list' => 'articles#list'
  post '/api/clubs/articles/detail/:article_id/list/delete' => 'articles#cutlist'
  post 'api/users/:uid/articles/:article_id/notes/create' => 'notes#create'
  resources :notes
  resources :users
  resources :clubs
  resources :articles

end

app/models/webmail.rb
class Webmail < ActiveRecord::Base
    validates :sender_id, :sender_name, :receiver_id, :receiver_type, :content, :ifread, presence: true
end

app/controllers/webmails_controller.rb
class WebmailsController < ApplicationController
  before_action :set_webmail, only: [:show, :edit, :update, :destroy]

  #POST /api/users/webmails/readone/:webmail_id
  def getcontent
    @webmail = Webmail.find(params[:webmail_id].to_i)
    if @webmail.nil?
       render text: 'Webmail not exit',status: 404    
    end
    if @webmail.ifread==0
       @webmail.ifread=1
    end
    a = []
    a<<{:webmail_id => @webmail.id,:sender_id => @webmail.sender_id,:sender_name=>@webmail.sender_name, :receiver_id => @webmail.receiver_id,:receiver_id,:content=>@webmail.content,:if_read=>@webmail.ifread} 
    render :json=>{:txt => a}.to_json, status:200 
  end

  # GET /webmails
  # GET /webmails.json
  def index
    @webmails = Webmail.all
  end

  # GET /webmails/1
  # GET /webmails/1.json
  def show
  end

  # GET /webmails/new
  def new
    @webmail = Webmail.new
  end

  # GET /webmails/1/edit
  def edit
  end

  # POST /webmails
  # POST /webmails.json
  def create
    @webmail = Webmail.new(webmail_params)

    respond_to do |format|
      if @webmail.save
        format.html { redirect_to @webmail, notice: 'Webmail was successfully created.' }
        format.json { render :show, status: :created, location: @webmail }
      else
        format.html { render :new }
        format.json { render json: @webmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webmails/1
  # PATCH/PUT /webmails/1.json
  def update
    respond_to do |format|
      if @webmail.update(webmail_params)
        format.html { redirect_to @webmail, notice: 'Webmail was successfully updated.' }
        format.json { render :show, status: :ok, location: @webmail }
      else
        format.html { render :edit }
        format.json { render json: @webmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmails/1
  # DELETE /webmails/1.json
  def destroy
    @webmail.destroy
    respond_to do |format|
      format.html { redirect_to webmails_url, notice: 'Webmail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webmail
      @webmail = Webmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webmail_params
      params.require(:webmail).permit(:sender_id, :sender_name, :receiver_id, :receiver_type, :content, :ifread)
    end
end

app/helpers/webmails_helper.rb
module WebmailsHelper
end

app/views/webmails/_form.html.erb
<%= form_for(@webmail) do |f| %>
  <% if @webmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@webmail.errors.count, "error") %> prohibited this webmail from being saved:</h2>

      <ul>
      <% @webmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :sender_name %><br>
    <%= f.text_field :sender_name %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br>
    <%= f.number_field :receiver_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_type %><br>
    <%= f.number_field :receiver_type %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :ifread %><br>
    <%= f.number_field :ifread %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webmails/edit.html.erb
<h1>Editing Webmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @webmail %> |
<%= link_to 'Back', webmails_path %>

app/views/webmails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Webmails</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Sender name</th>
      <th>Receiver</th>
      <th>Receiver type</th>
      <th>Content</th>
      <th>Ifread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webmails.each do |webmail| %>
      <tr>
        <td><%= webmail.sender_id %></td>
        <td><%= webmail.sender_name %></td>
        <td><%= webmail.receiver_id %></td>
        <td><%= webmail.receiver_type %></td>
        <td><%= webmail.content %></td>
        <td><%= webmail.ifread %></td>
        <td><%= link_to 'Show', webmail %></td>
        <td><%= link_to 'Edit', edit_webmail_path(webmail) %></td>
        <td><%= link_to 'Destroy', webmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webmail', new_webmail_path %>

app/views/webmails/new.html.erb
<h1>New Webmail</h1>

<%= render 'form' %>

<%= link_to 'Back', webmails_path %>

app/views/webmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @webmail.sender_id %>
</p>

<p>
  <strong>Sender name:</strong>
  <%= @webmail.sender_name %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @webmail.receiver_id %>
</p>

<p>
  <strong>Receiver type:</strong>
  <%= @webmail.receiver_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @webmail.content %>
</p>

<p>
  <strong>Ifread:</strong>
  <%= @webmail.ifread %>
</p>

<%= link_to 'Edit', edit_webmail_path(@webmail) %> |
<%= link_to 'Back', webmails_path %>