config/routes.rb
Rails.application.routes.draw do
  

 
  resources :phone_nums
  match '/api/*other' => 'notes#opt', via: [:options]

  get '/api/users/clubs/abstracts/:category' => 'clubs#clubsbycategory' #按社团类别返回对应的社团列表
  get '/api/articles/activities/:page_id' => 'clubs#clubsactivity'#返回一个社团>的活动
  get '/api/users/clubs/abstract/:page_id' => 'clubs#clublist'#返回社团列表
  get '/api/clubs/detail' => 'clubs#returnmm'  #返回社团人数

  resources :comments
  resources :webmails
  resources :lists

  post '/api/users/register/checkiden' => 'users#checkiden' # 实名验证

  get '/api/articles/:article_id/comments' => 'comments#getcomments' # 获得当前文章评论

  post '/api/users/phone_num/verify/code' => 'users#verify_phone_sendcode'# 手机验证发送验证码
  post '/api/users/phone_num/verify' => 'users#verify_phone' # 验证验证码是否正确
  post 'GET /api/users/email/verify' => 'users#verify_email_send' # 验证邮箱，给邮箱寄信
  get '/api/users/email/verify/:uid/:hash_code' => 'users#verify_email' # 验证邮箱，邮箱点击链接返回

  post '/api/users/forgetpassword/email' => 'users#fp_email' # 忘记密码，邮箱
  get '/api/users/forgetpassword/email/verify/:uid/:hash_code' => 'users#fp_email_verify' # 忘记密码，邮箱转跳
  post '/api/users/forgetpassword/phone_num/send' => 'users#fp_phone_send' # 忘记密码，手机
  post '/api/users/forgetpassword/phone_num/verify' => 'users#fp_phone_verify' # 忘记密码，手机
  
  get '/api/users/detail' => 'users#detail'#返回个人信息
  post '/api/users/statistics' => 'users#statistics'#返回用户参加的社团个数和报名活动个数
  get '/api/users/clubs/all' => 'users#clublist'  
  get '/api/users/articles/activities/all' => 'users#activitylist'

  get '/api/clubs/members/all' => 'clubs#memberslist'#获取社团名单
  get 'api/clubs/users/export/:uid' => 'clubs#exportlist' #导出名单
  post '/api/clubs/members/forcequit' => 'clubs#forcequit' #强制退社
  get '/api/clubs/members/apply' => 'clubs#applicationlist' #申请人列表
  post '/api/clubs/members/apply/accept' => 'clubs#acceptapplication'#同意申请
  post '/api/clubs/members/apply/refuse' => 'clubs#refuseapplication'#拒绝申请  

  resources :informs
  resources :applications

  get '/api/users/register/check/:uid' => 'users#checkuid'
  post '/api/register' => 'users#register'
  post '/api/clubs/login' => 'clubs#login'
  post '/api/users/login' => 'users#login'
  post '/api/users/get_token_for_app' => 'users#get_token_for_app'
  get '/api/articles/:page_id/:club_id/:kind' => 'articles#abstracts'
  get '/api/articles/detail/:article_id' => 'articles#detail'
  get '/api/clubs/:uid/articles/:page_id' => 'clubs#getabstracts'
  get '/api/users/logout' => 'users#logout'
  get '/api/clubs/logout' => 'clubs#logout'
  post '/api/clubs/inform' => 'clubs#inform'
  post '/api/clubs/articles/:article_id/comments/reply/:reply_id' => 'clubs#reply'
  post '/api/users/articles/:article_id/comments/reply/:reply_id' => 'users#reply'
  post '/api/users/webmails/readall' => 'users#readall'
  post '/api/clubs/webmails/readall' => 'clubs#readall'
  post '/api/users/webmails/usergetcontent/:webmail_id' => 'users#usergetcontent'
   post '/api/clubs/webmails/clubgetcontent/:webmail_id' => 'clubs#clubgetcontent'
  post '/api/users/clubs/apply/:club_id' => 'users#apply'
  get '/api/users/articles/activities/cancel/:article_id' => 'users#cancel'

  get '/api/clubs/informs/all' => 'clubs#getinform'
  post '/api/clubs/articles/detail/create' => 'articles#create'
  post '/api/clubs/articles/detail/:article_id/change' => 'articles#show'
  post '/api/clubs/articles/detail/:article_id/update' => 'articles#update'
  post '/api/clubs/articles/detail/:article_id/delete' => 'articles#destroy' 
  post '/api/clubs/articles/detail/:article_id/list' => 'articles#list'
  post '/api/clubs/articles/detail/:article_id/list/delete' => 'articles#cutlist'
  post 'api/users/:uid/articles/:article_id/notes/create' => 'notes#create'
  resources :notes
  resources :users
  resources :clubs
  resources :articles

end

app/models/phone_num.rb
class PhoneNum < ActiveRecord::Base
end

app/controllers/phone_nums_controller.rb
class PhoneNumsController < ApplicationController
  before_action :set_phone_num, only: [:show, :edit, :update, :destroy]

  # GET /phone_nums
  # GET /phone_nums.json
  def index
    @phone_nums = PhoneNum.all
  end

  # GET /phone_nums/1
  # GET /phone_nums/1.json
  def show
  end

  # GET /phone_nums/new
  def new
    @phone_num = PhoneNum.new
  end

  # GET /phone_nums/1/edit
  def edit
  end

  # POST /phone_nums
  # POST /phone_nums.json
  def create
    @phone_num = PhoneNum.new(phone_num_params)

    respond_to do |format|
      if @phone_num.save
        format.html { redirect_to @phone_num, notice: 'Phone num was successfully created.' }
        format.json { render :show, status: :created, location: @phone_num }
      else
        format.html { render :new }
        format.json { render json: @phone_num.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_nums/1
  # PATCH/PUT /phone_nums/1.json
  def update
    respond_to do |format|
      if @phone_num.update(phone_num_params)
        format.html { redirect_to @phone_num, notice: 'Phone num was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_num }
      else
        format.html { render :edit }
        format.json { render json: @phone_num.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_nums/1
  # DELETE /phone_nums/1.json
  def destroy
    @phone_num.destroy
    respond_to do |format|
      format.html { redirect_to phone_nums_url, notice: 'Phone num was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_num
      @phone_num = PhoneNum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_num_params
      params.require(:phone_num).permit(:phone_num, :phone_verify_num)
    end
end

app/helpers/phone_nums_helper.rb
module PhoneNumsHelper
end

app/views/phone_nums/_form.html.erb
<%= form_for(@phone_num) do |f| %>
  <% if @phone_num.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_num.errors.count, "error") %> prohibited this phone_num from being saved:</h2>

      <ul>
      <% @phone_num.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_num %><br>
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :phone_verify_num %><br>
    <%= f.number_field :phone_verify_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_nums/edit.html.erb
<h1>Editing Phone Num</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_num %> |
<%= link_to 'Back', phone_nums_path %>

app/views/phone_nums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phone Nums</h1>

<table>
  <thead>
    <tr>
      <th>Phone num</th>
      <th>Phone verify num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_nums.each do |phone_num| %>
      <tr>
        <td><%= phone_num.phone_num %></td>
        <td><%= phone_num.phone_verify_num %></td>
        <td><%= link_to 'Show', phone_num %></td>
        <td><%= link_to 'Edit', edit_phone_num_path(phone_num) %></td>
        <td><%= link_to 'Destroy', phone_num, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone num', new_phone_num_path %>

app/views/phone_nums/new.html.erb
<h1>New Phone Num</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_nums_path %>

app/views/phone_nums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone num:</strong>
  <%= @phone_num.phone_num %>
</p>

<p>
  <strong>Phone verify num:</strong>
  <%= @phone_num.phone_verify_num %>
</p>

<%= link_to 'Edit', edit_phone_num_path(@phone_num) %> |
<%= link_to 'Back', phone_nums_path %>